package com.tap.zoot.audio

/** Plays stereo, signed 16-bit PCM generated by the guest. */
interface AudioOutput : AutoCloseable {
    var volume: Float

    /** The input is borrowed for this call. Returns the number of accepted stereo frames. */
    fun submit(
        pcm: ByteArray,
        offset: Int,
        frameCount: Int,
        sampleRate: Int,
    ): Int

    fun pause()

    fun resume()
}
